[package]
name = "cfg"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
git2 = "0.13"
tokio = { version = "1", features = ["full"] }

